{% set name = "types-pathlib2" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-pathlib2-{{ version }}.tar.gz
  sha256: 996981d3c39a3dd592bac06b4d87257c623f1acc3eef672f823d85c528b7a6ed

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/pathlib2-python2-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pathlib2
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
